/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.12.v202002200719.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_GREATWALL_TBOX_SPE_Location_5_G_PROXY_HPP_
#define V1_GREATWALL_TBOX_SPE_Location_5_G_PROXY_HPP_

#include <v1/GREATWALL/TBOX/SPELocation_5GProxyBase.hpp>


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <CommonAPI/AttributeExtension.hpp>
#include <CommonAPI/Factory.hpp>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace v1 {
namespace GREATWALL {
namespace TBOX {

template <typename ... _AttributeExtensions>
class SPELocation_5GProxy
    : virtual public SPELocation_5G,
      virtual public SPELocation_5GProxyBase,
      virtual public _AttributeExtensions... {
public:
    SPELocation_5GProxy(std::shared_ptr<CommonAPI::Proxy> delegate);
    ~SPELocation_5GProxy();

    typedef SPELocation_5G InterfaceType;


    /**
     * Returns the wrapper class that provides access to the attribute NtfSPELocation.
     */
    virtual NtfSPELocationAttribute& getNtfSPELocationAttribute() {
        return delegate_->getNtfSPELocationAttribute();
    }




    /**
     * Returns the CommonAPI address of the remote partner this proxy communicates with.
     */
    virtual const CommonAPI::Address &getAddress() const;

    /**
     * Returns true if the remote partner for this proxy is currently known to be available.
     */
    virtual bool isAvailable() const;

    /**
     * Returns true if the remote partner for this proxy is available.
     */
    virtual bool isAvailableBlocking() const;

    /**
     * Returns the wrapper class that is used to (de-)register for notifications about
     * the availability of the remote partner of this proxy.
     */
    virtual CommonAPI::ProxyStatusEvent& getProxyStatusEvent();

    /**
     * Returns the wrapper class that is used to access version information of the remote
     * partner of this proxy.
     */
    virtual CommonAPI::InterfaceVersionAttribute& getInterfaceVersionAttribute();

 private:
    std::shared_ptr< SPELocation_5GProxyBase> delegate_;
};

typedef SPELocation_5GProxy<> SPELocation_5GProxyDefault;

namespace SPELocation_5GExtensions {
    template <template <typename > class _ExtensionType>
    class NtfSPELocationAttributeExtension {
     public:
        typedef _ExtensionType< SPELocation_5GProxyBase::NtfSPELocationAttribute> extension_type;
    
        static_assert(std::is_base_of<typename CommonAPI::AttributeExtension< SPELocation_5GProxyBase::NtfSPELocationAttribute>, extension_type>::value,
                      "Not CommonAPI Attribute Extension!");
    
        NtfSPELocationAttributeExtension(SPELocation_5GProxyBase& proxy): attributeExtension_(proxy.getNtfSPELocationAttribute()) {
        }
    
        inline extension_type& getNtfSPELocationAttributeExtension() {
            return attributeExtension_;
        }
    
     private:
        extension_type attributeExtension_;
    };

} // namespace SPELocation_5GExtensions

//
// SPELocation_5GProxy Implementation
//
template <typename ... _AttributeExtensions>
SPELocation_5GProxy<_AttributeExtensions...>::SPELocation_5GProxy(std::shared_ptr<CommonAPI::Proxy> delegate):
        _AttributeExtensions(*(std::dynamic_pointer_cast< SPELocation_5GProxyBase>(delegate)))...,
        delegate_(std::dynamic_pointer_cast< SPELocation_5GProxyBase>(delegate)) {
}

template <typename ... _AttributeExtensions>
SPELocation_5GProxy<_AttributeExtensions...>::~SPELocation_5GProxy() {
}


template <typename ... _AttributeExtensions>
const CommonAPI::Address &SPELocation_5GProxy<_AttributeExtensions...>::getAddress() const {
    return delegate_->getAddress();
}

template <typename ... _AttributeExtensions>
bool SPELocation_5GProxy<_AttributeExtensions...>::isAvailable() const {
    return delegate_->isAvailable();
}

template <typename ... _AttributeExtensions>
bool SPELocation_5GProxy<_AttributeExtensions...>::isAvailableBlocking() const {
    return delegate_->isAvailableBlocking();
}

template <typename ... _AttributeExtensions>
CommonAPI::ProxyStatusEvent& SPELocation_5GProxy<_AttributeExtensions...>::getProxyStatusEvent() {
    return delegate_->getProxyStatusEvent();
}

template <typename ... _AttributeExtensions>
CommonAPI::InterfaceVersionAttribute& SPELocation_5GProxy<_AttributeExtensions...>::getInterfaceVersionAttribute() {
    return delegate_->getInterfaceVersionAttribute();
}


} // namespace TBOX
} // namespace GREATWALL
} // namespace v1

namespace CommonAPI {
template<template<typename > class _AttributeExtension>
struct DefaultAttributeProxyHelper< ::v1::GREATWALL::TBOX::SPELocation_5GProxy,
    _AttributeExtension> {
    typedef typename ::v1::GREATWALL::TBOX::SPELocation_5GProxy<
            ::v1::GREATWALL::TBOX::SPELocation_5GExtensions::NtfSPELocationAttributeExtension<_AttributeExtension>
    > class_t;
};
}


// Compatibility
namespace v1_0 = v1;

#endif // V1_GREATWALL_TBOX_SPE_Location_5_G_PROXY_HPP_
