/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.12.v202002200719.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_GREATWALL_TBOX_T_BOX_TSP_COM_INSTANCE_HPP_
#define V1_GREATWALL_TBOX_T_BOX_TSP_COM_INSTANCE_HPP_

#include <string>

namespace v1 {
namespace GREATWALL {
namespace TBOX {

const char * const TBoxTSPCom_TBoxTSPCom01 = "TBoxTSPCom01";

const std::string TBoxTSPCom_INSTANCES[] = {
    TBoxTSPCom_TBoxTSPCom01
};

} // namespace TBOX
} // namespace GREATWALL
} // namespace v1

// Compatibility
namespace v1_0 = v1;

#endif // V1_GREATWALL_TBOX_T_BOX_TSP_COM_INSTANCE_HPP_
