/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.someip 3.1.12.v202002200807.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/

#ifndef V1_GREATWALL_TBOX_T_Box_Telephony_SOMEIP_DEPLOYMENT_HPP_
#define V1_GREATWALL_TBOX_T_Box_Telephony_SOMEIP_DEPLOYMENT_HPP_


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif
#include <CommonAPI/SomeIP/Deployment.hpp>
#undef COMMONAPI_INTERNAL_COMPILATION

namespace v1 {
namespace GREATWALL {
namespace TBOX {
namespace TBoxTelephony_ {

// Interface-specific deployment types
typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> TBoxCallTypeDeployment_t;
typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> TBoxResponseDeployment_t;
typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> TBoxSimModeDeployment_t;
typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> TBoxSimStateDeployment_t;
typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> TBoxCallOperationDeployment_t;
typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> TBoxNetTypeDeployment_t;
typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> TBoxCallStateDeployment_t;
typedef CommonAPI::SomeIP::ArrayDeployment<
    CommonAPI::SomeIP::IntegerDeployment<uint8_t>
> TBoxTelephoneNumberDeployment_t;
typedef CommonAPI::SomeIP::StructDeployment<
    CommonAPI::SomeIP::IntegerDeployment<uint16_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint8_t>,
    CommonAPI::SomeIP::StringDeployment
> TBoxNetworkProviderStructDeployment_t;
typedef CommonAPI::SomeIP::IntegerDeployment<uint16_t> MCCDeployment_t;
typedef CommonAPI::SomeIP::StringDeployment NetworkProviderDeployment_t;
typedef CommonAPI::SomeIP::IntegerDeployment<uint8_t> MNCDeployment_t;
typedef CommonAPI::SomeIP::StringDeployment IMSIDeployment_t;
typedef CommonAPI::SomeIP::StructDeployment<
    ::v1::GREATWALL::TBOX::TBoxTelephony_::TBoxSimStateDeployment_t,
    ::v1::GREATWALL::TBOX::TBoxTelephony_::TBoxSimModeDeployment_t
> TBoxSimStatusStructDeployment_t;
typedef CommonAPI::SomeIP::IntegerDeployment<int64_t> long64Deployment_t;
typedef CommonAPI::SomeIP::StringDeployment IMEIDeployment_t;
typedef CommonAPI::SomeIP::StringDeployment ICCIDDeployment_t;
typedef CommonAPI::SomeIP::StructDeployment<
    ::v1::GREATWALL::TBOX::TBoxTelephony_::TBoxNetTypeDeployment_t,
    CommonAPI::SomeIP::IntegerDeployment<int16_t>
> TBoxSignalStrengthStructDeployment_t;
typedef CommonAPI::SomeIP::IntegerDeployment<int16_t> SignalStrenghRawDataDeployment_t;

// Type-specific deployments
COMMONAPI_EXPORT extern ::v1::GREATWALL::TBOX::TBoxTelephony_::TBoxTelephoneNumberDeployment_t TBoxTelephoneNumberDeployment;
COMMONAPI_EXPORT extern ::v1::GREATWALL::TBOX::TBoxTelephony_::TBoxNetworkProviderStructDeployment_t TBoxNetworkProviderStructDeployment;

// Attribute-specific deployments

// Argument-specific deployment
COMMONAPI_EXPORT extern CommonAPI::SomeIP::StringDeployment TBoxSIMInfor_ICCIDDeployment;
COMMONAPI_EXPORT extern CommonAPI::SomeIP::StringDeployment TBoxSIMInfor_IMEIDeployment;
COMMONAPI_EXPORT extern CommonAPI::SomeIP::StringDeployment TBoxSIMInfor_IMSIDeployment;

// Broadcast-specific deployments

} // namespace TBoxTelephony_
} // namespace TBOX
} // namespace GREATWALL
} // namespace v1

#endif // V1_GREATWALL_TBOX_T_Box_Telephony_SOMEIP_DEPLOYMENT_HPP_
