/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.someip 3.1.12.v202002200807.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#include <v1/GREATWALL/TBOX/TBoxV2XSystemFunctionsSomeIPDeployment.hpp>

namespace v1 {
namespace GREATWALL {
namespace TBOX {
namespace TBoxV2XSystemFunctions_ {

// Type-specific deployments

// Attribute-specific deployments

// Argument-specific deployment

// Broadcast-specific deployments

} // namespace TBoxV2XSystemFunctions_
} // namespace TBOX
} // namespace GREATWALL
} // namespace v1
