/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.12.v202002200719.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#include <v1/GREATWALL/TBOX/TBoxTSPSystemFunctionsStubDefault.hpp>
#include <assert.h>

namespace v1 {
namespace GREATWALL {
namespace TBOX {

TBoxTSPSystemFunctionsStubDefault::TBoxTSPSystemFunctionsStubDefault():
        remoteEventHandler_(this),
        interfaceVersion_(TBoxTSPSystemFunctions::getInterfaceVersion()) {
}

const CommonAPI::Version& TBoxTSPSystemFunctionsStubDefault::getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) {
    (void)_client;
    return interfaceVersion_;
}

TBoxTSPSystemFunctionsStubRemoteEvent* TBoxTSPSystemFunctionsStubDefault::initStubAdapter(const std::shared_ptr< TBoxTSPSystemFunctionsStubAdapter> &_adapter) {
    CommonAPI::Stub<TBoxTSPSystemFunctionsStubAdapter, TBoxTSPSystemFunctionsStubRemoteEvent>::stubAdapter_ = _adapter;
    return &remoteEventHandler_;
}


void TBoxTSPSystemFunctionsStubDefault::StsRequest(const std::shared_ptr<CommonAPI::ClientId> _client, TBoxTSPSystemFunctions::StsRequest _StsRequest) {
    (void)_client;
    (void)_StsRequest;
}

void TBoxTSPSystemFunctionsStubDefault::RegisterRequest(const std::shared_ptr<CommonAPI::ClientId> _client, TBoxTSPSystemFunctions::RegisterRequest _RegisterRequest) {
    (void)_client;
    (void)_RegisterRequest;
}


void TBoxTSPSystemFunctionsStubDefault::fireStsResponseEvent(const ::v1::GREATWALL::TBOX::TBoxTSPSystemFunctions::StsResponse &_StsResponse) {
    if (!_StsResponse.validate()) {
        return;
    }
    TBoxTSPSystemFunctionsStub::fireStsResponseEvent(_StsResponse);
}
void TBoxTSPSystemFunctionsStubDefault::fireStsContentEvent(const ::v1::GREATWALL::TBOX::TBoxTSPSystemFunctions::StsContent &_StsContent) {
    TBoxTSPSystemFunctionsStub::fireStsContentEvent(_StsContent);
}
void TBoxTSPSystemFunctionsStubDefault::fireRegisterContentEvent(const ::v1::GREATWALL::TBOX::TBoxTSPSystemFunctions::RegisterContent &_RegisterContent) {
    TBoxTSPSystemFunctionsStub::fireRegisterContentEvent(_RegisterContent);
}
void TBoxTSPSystemFunctionsStubDefault::fireRegisterResponseEvent(const ::v1::GREATWALL::TBOX::TBoxTSPSystemFunctions::RegisterResponse &_RegisterResponse) {
    if (!_RegisterResponse.validate()) {
        return;
    }
    TBoxTSPSystemFunctionsStub::fireRegisterResponseEvent(_RegisterResponse);
}


TBoxTSPSystemFunctionsStubDefault::RemoteEventHandler::RemoteEventHandler(TBoxTSPSystemFunctionsStubDefault *_defaultStub)
    : 
      defaultStub_(_defaultStub) {
}

} // namespace TBOX
} // namespace GREATWALL
} // namespace v1
