/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.12.v202002200719.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_GREATWALL_IDC1_5_IDC1_5_System_Functions_PROXY_BASE_HPP_
#define V1_GREATWALL_IDC1_5_IDC1_5_System_Functions_PROXY_BASE_HPP_

#include <v1/GREATWALL/IDC1_5/IDC1_5SystemFunctions.hpp>



#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <CommonAPI/Deployment.hpp>
#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Struct.hpp>
#include <cstdint>
#include <vector>

#include <CommonAPI/Event.hpp>
#include <CommonAPI/Proxy.hpp>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace v1 {
namespace GREATWALL {
namespace IDC1_5 {

class IDC1_5SystemFunctionsProxyBase
    : virtual public CommonAPI::Proxy {
public:
    typedef CommonAPI::Event<
        ::v1::GREATWALL::IDC1_5::IDC1_5SystemFunctions::DataCollectTriggerStruct
    > VideoUploadEvent;



    virtual VideoUploadEvent& getVideoUploadEvent() = 0;

};

} // namespace IDC1_5
} // namespace GREATWALL
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_GREATWALL_IDC1_5_IDC1_5_System_Functions_PROXY_BASE_HPP_
