/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.12.v202002200719.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_GREATWALL_IDC_L2_IDC1_5_IDC3_0_MDC_A_ADAS_Display_Information_STUB_HPP_
#define V1_GREATWALL_IDC_L2_IDC1_5_IDC3_0_MDC_A_ADAS_Display_Information_STUB_HPP_

#include <functional>
#include <sstream>




#include <v1/GREATWALL/IDC_L2_IDC1_5_IDC3_0_MDC_A/ADASDisplayInformation.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <cstdint>
#include <unordered_set>
#include <vector>


#include <CommonAPI/Stub.hpp>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace v1 {
namespace GREATWALL {
namespace IDC_L2_IDC1_5_IDC3_0_MDC_A {

/**
 * Receives messages from remote and handles all dispatching of deserialized calls
 * to a stub for the service ADASDisplayInformation. Also provides means to send broadcasts
 * and attribute-changed-notifications of observable attributes as defined by this service.
 * An application developer should not need to bother with this class.
 */
class ADASDisplayInformationStubAdapter
    : public virtual CommonAPI::StubAdapter,
      public virtual ADASDisplayInformation {
 public:

    /**
    * Sends a broadcast event for LocationDisp. Should not be called directly.
    * Instead, the "fire<broadcastName>Event" methods of the stub should be used.
    */
    virtual void fireLocationDispEvent(const ::v1::GREATWALL::IDC_L2_IDC1_5_IDC3_0_MDC_A::ADASDisplayInformation::LaneChangeZone &_LaneChangeZone) = 0;
    /**
    * Sends a broadcast event for GuideLineCoordinate. Should not be called directly.
    * Instead, the "fire<broadcastName>Event" methods of the stub should be used.
    */
    virtual void fireGuideLineCoordinateEvent(const ::v1::GREATWALL::IDC_L2_IDC1_5_IDC3_0_MDC_A::ADASDisplayInformation::Guide_Line_Points_Array &_Guide_Line_Points_Array) = 0;


    virtual void deactivateManagedInstances() = 0;


protected:
    /**
     * Defines properties for storing the ClientIds of clients / proxies that have
     * subscribed to the selective broadcasts
     */

};

/**
 * Defines the necessary callbacks to handle remote set events related to the attributes
 * defined in the IDL description for ADASDisplayInformation.
 * For each attribute two callbacks are defined:
 * - a verification callback that allows to verify the requested value and to prevent setting
 *   e.g. an invalid value ("onRemoteSet<AttributeName>").
 * - an action callback to do local work after the attribute value has been changed
 *   ("onRemote<AttributeName>Changed").
 *
 * This class and the one below are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class ADASDisplayInformationStubRemoteEvent
{
public:
    virtual ~ADASDisplayInformationStubRemoteEvent() { }

};

/**
 * Defines the interface that must be implemented by any class that should provide
 * the service ADASDisplayInformation to remote clients.
 * This class and the one above are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class ADASDisplayInformationStub
    : public virtual CommonAPI::Stub<ADASDisplayInformationStubAdapter, ADASDisplayInformationStubRemoteEvent>
{
public:

    virtual ~ADASDisplayInformationStub() {}
    virtual const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> clientId) = 0;
    void lockInterfaceVersionAttribute(bool _lockAccess) { static_cast<void>(_lockAccess); }


    /// Sends a broadcast event for LocationDisp.
    virtual void fireLocationDispEvent(const ::v1::GREATWALL::IDC_L2_IDC1_5_IDC3_0_MDC_A::ADASDisplayInformation::LaneChangeZone &_LaneChangeZone) {
        auto stubAdapter = CommonAPI::Stub<ADASDisplayInformationStubAdapter, ADASDisplayInformationStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->fireLocationDispEvent(_LaneChangeZone);
    }
    /// Sends a broadcast event for GuideLineCoordinate.
    virtual void fireGuideLineCoordinateEvent(const ::v1::GREATWALL::IDC_L2_IDC1_5_IDC3_0_MDC_A::ADASDisplayInformation::Guide_Line_Points_Array &_Guide_Line_Points_Array) {
        auto stubAdapter = CommonAPI::Stub<ADASDisplayInformationStubAdapter, ADASDisplayInformationStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->fireGuideLineCoordinateEvent(_Guide_Line_Points_Array);
    }

    
    using CommonAPI::Stub<ADASDisplayInformationStubAdapter, ADASDisplayInformationStubRemoteEvent>::initStubAdapter;
    typedef CommonAPI::Stub<ADASDisplayInformationStubAdapter, ADASDisplayInformationStubRemoteEvent>::StubAdapterType StubAdapterType;
    typedef CommonAPI::Stub<ADASDisplayInformationStubAdapter, ADASDisplayInformationStubRemoteEvent>::RemoteEventHandlerType RemoteEventHandlerType;
    typedef ADASDisplayInformationStubRemoteEvent RemoteEventType;
    typedef ADASDisplayInformation StubInterface;
};

} // namespace IDC_L2_IDC1_5_IDC3_0_MDC_A
} // namespace GREATWALL
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_GREATWALL_IDC_L2_IDC1_5_IDC3_0_MDC_A_ADAS_Display_Information_STUB_HPP_
