/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.12.v202002200719.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_GREATWALL_IDC_L2_IDC1_5_IDC3_0_MDC_A_ADAS_DISPLAY_INFORMATION_INSTANCE_HPP_
#define V1_GREATWALL_IDC_L2_IDC1_5_IDC3_0_MDC_A_ADAS_DISPLAY_INFORMATION_INSTANCE_HPP_

#include <string>

namespace v1 {
namespace GREATWALL {
namespace IDC_L2_IDC1_5_IDC3_0_MDC_A {

const char * const ADASDisplayInformation_ADASDisplayInformation01 = "ADASDisplayInformation01";

const std::string ADASDisplayInformation_INSTANCES[] = {
    ADASDisplayInformation_ADASDisplayInformation01
};

} // namespace IDC_L2_IDC1_5_IDC3_0_MDC_A
} // namespace GREATWALL
} // namespace v1

// Compatibility
namespace v1_0 = v1;

#endif // V1_GREATWALL_IDC_L2_IDC1_5_IDC3_0_MDC_A_ADAS_DISPLAY_INFORMATION_INSTANCE_HPP_
