/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.12.v202002200719.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#include <v1/GREATWALL/IDC_L2_IDC1_5_IDC3_0_MDC_A/ADASDisplayInformationStubDefault.hpp>
#include <assert.h>

namespace v1 {
namespace GREATWALL {
namespace IDC_L2_IDC1_5_IDC3_0_MDC_A {

ADASDisplayInformationStubDefault::ADASDisplayInformationStubDefault():
        remoteEventHandler_(this),
        interfaceVersion_(ADASDisplayInformation::getInterfaceVersion()) {
}

const CommonAPI::Version& ADASDisplayInformationStubDefault::getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) {
    (void)_client;
    return interfaceVersion_;
}

ADASDisplayInformationStubRemoteEvent* ADASDisplayInformationStubDefault::initStubAdapter(const std::shared_ptr< ADASDisplayInformationStubAdapter> &_adapter) {
    CommonAPI::Stub<ADASDisplayInformationStubAdapter, ADASDisplayInformationStubRemoteEvent>::stubAdapter_ = _adapter;
    return &remoteEventHandler_;
}



void ADASDisplayInformationStubDefault::fireLocationDispEvent(const ::v1::GREATWALL::IDC_L2_IDC1_5_IDC3_0_MDC_A::ADASDisplayInformation::LaneChangeZone &_LaneChangeZone) {
    if (!_LaneChangeZone.validate()) {
        return;
    }
    ADASDisplayInformationStub::fireLocationDispEvent(_LaneChangeZone);
}
void ADASDisplayInformationStubDefault::fireGuideLineCoordinateEvent(const ::v1::GREATWALL::IDC_L2_IDC1_5_IDC3_0_MDC_A::ADASDisplayInformation::Guide_Line_Points_Array &_Guide_Line_Points_Array) {
    ADASDisplayInformationStub::fireGuideLineCoordinateEvent(_Guide_Line_Points_Array);
}


ADASDisplayInformationStubDefault::RemoteEventHandler::RemoteEventHandler(ADASDisplayInformationStubDefault *_defaultStub)
    : 
      defaultStub_(_defaultStub) {
}

} // namespace IDC_L2_IDC1_5_IDC3_0_MDC_A
} // namespace GREATWALL
} // namespace v1
