/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.someip 3.1.12.v202002200807.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#include <v1/GREATWALL/AVP/AVPSystemFunctionsSomeIPDeployment.hpp>

namespace v1 {
namespace GREATWALL {
namespace AVP {
namespace AVPSystemFunctions_ {

// Type-specific deployments
::v1::GREATWALL::AVP::AVPSystemFunctions_::ParkingListStructArrayDeployment_t ParkingListStructArrayDeployment(&::v1::GREATWALL::AVP::AVPSystemFunctions_::ParkingListStructDeployment, 0, 0, 4);
::v1::GREATWALL::AVP::AVPSystemFunctions_::ParkingListStructDeployment_t ParkingListStructDeployment(4, static_cast< ::v1::GREATWALL::AVP::AVPSystemFunctions_::idDeployment_t* >(nullptr), static_cast< ::v1::GREATWALL::AVP::AVPSystemFunctions_::nameDeployment_t* >(nullptr), static_cast< ::v1::GREATWALL::AVP::AVPSystemFunctions_::addressDeployment_t* >(nullptr), static_cast< ::v1::GREATWALL::AVP::AVPSystemFunctions_::lonDeployment_t* >(nullptr), static_cast< ::v1::GREATWALL::AVP::AVPSystemFunctions_::latDeployment_t* >(nullptr), static_cast< ::v1::GREATWALL::AVP::AVPSystemFunctions_::distanceDeployment_t* >(nullptr), static_cast< ::v1::GREATWALL::AVP::AVPSystemFunctions_::idle_numDeployment_t* >(nullptr), static_cast< ::v1::GREATWALL::AVP::AVPSystemFunctions_::total_numDeployment_t* >(nullptr), static_cast< ::v1::GREATWALL::AVP::AVPSystemFunctions_::floorsDeployment_t* >(nullptr));
::v1::GREATWALL::AVP::AVPSystemFunctions_::PathInfoStructArrayDeployment_t PathInfoStructArrayDeployment(&::v1::GREATWALL::AVP::AVPSystemFunctions_::PathInfoStructDeployment, 0, 0, 4);
::v1::GREATWALL::AVP::AVPSystemFunctions_::PathInfoStructDeployment_t PathInfoStructDeployment(4, static_cast< ::v1::GREATWALL::AVP::AVPSystemFunctions_::PathIdDeployment_t* >(nullptr), static_cast< ::v1::GREATWALL::AVP::AVPSystemFunctions_::PathNumDeployment_t* >(nullptr), static_cast< ::v1::GREATWALL::AVP::AVPSystemFunctions_::PathTypeDeployment_t* >(nullptr), static_cast< ::v1::GREATWALL::AVP::AVPSystemFunctions_::PathLotTypeDeployment_t* >(nullptr), static_cast< ::v1::GREATWALL::AVP::AVPSystemFunctions_::PathStatusDeployment_t* >(nullptr), static_cast< ::v1::GREATWALL::AVP::AVPSystemFunctions_::PathLearnRateDeployment_t* >(nullptr), static_cast< ::v1::GREATWALL::AVP::AVPSystemFunctions_::PathDistanceDeployment_t* >(nullptr), static_cast< ::v1::GREATWALL::AVP::AVPSystemFunctions_::PathNameDeployment_t* >(nullptr), static_cast< ::v1::GREATWALL::AVP::AVPSystemFunctions_::PathPicDeployment_t* >(nullptr));

// Attribute-specific deployments

// Argument-specific deployment

// Broadcast-specific deployments

} // namespace AVPSystemFunctions_
} // namespace AVP
} // namespace GREATWALL
} // namespace v1
